CourierMB/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'^courierMB/', include('courier_mb.urls', namespace='courier_mb')),
    url(r'^start/', views.start_page),
    url(r'^admin/', admin.site.urls),
]

courier_mb/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from . import actions
from django.conf.urls import include
from rest_framework import routers
from django.contrib.auth import views as auth_views




urlpatterns = [

    #actions
    url(r'^actions/save_package/$', actions.save_package, name="save_package"),
    url(r'^actions/run_computations/$', actions.run_computations, name="run_computations"),
    url(r'^actions/get_airport/$', actions.get_airport, name="get_airport"),
    url(r'^actions/logout/$',actions.logout_action, name="logout"),
    url(r'^actions/init_database/$',actions.init_database, name="init_database"),
    url(r'^actions/add_to_database/$', actions.add_to_database, name="add_to_database"),
    url(r'^actions/clear_database/$', actions.clear_database, name="clear_database"),
    url(r'^actions/remove_packages/$', actions.remove_packages, name="remove_packages"),

    #views
    url(r'^home/$', views.get_home_page, name="home_page"),
    url(r'^package_details/$', views.get_package_details_page, name="package_details_page"),
    url(r'^profile/$', views.get_my_profile, name="my_profile"),
    url(r'^login/$', views.get_login_form, name="login_form"),
    url(r'^admin_panel/$', views.get_admin_panel, name="admin_panel"),
    url(r'^signup/$', views.get_signup_form, name="sign_up_form"),
    url(r'^send_inter_package/$', views.get_send_package_page, name="send_package_page"),
]

courier_mb/models.py
# Create your models here.
from django.db import models
from courier_mb.air_fracht_algo.model.package_status import PackageStatus
from django.contrib.auth.models import User
from courier_mb.air_fracht_algo.controller.airports_context import *
"""
        Airport details:
        * airport name,
        * landing/take-off price,
        * noise price,
        * parking price(after free time, per 12 hours),
        * fuel cost: price/1l,
        * cargo price: price/1kg
        """
class Airport(models.Model):
    """
        def __init__(self, name: str, lat: float, long:  float, land_take_off_price, noise_price, park_price, fuel_cost, cargo_price, *args, **kwargs):
            self.name = name
            self.lat = lat
            self.long = long
            self.land_take_off_price = land_take_off_price
            self.noise_price = noise_price
            self.park_price = park_price
            self.fuel_cost = fuel_cost
            self.cargo_price = cargo_price
            self.airport_dests = []
            self.packages = []
            self.packs_dest = {}
    """

    name = models.CharField(max_length=25)
    lat = models.FloatField()
    long = models.FloatField()
    land_take_off_price = models.FloatField()
    noise_price = models.FloatField()
    park_price = models.FloatField()
    fuel_cost = models.FloatField()
    cargo_price = models.FloatField()


    def __init__(self,id, name: str, lat: float, long:  float, land_take_off_price, noise_price,
                 park_price, fuel_cost, cargo_price, *args, **kwargs):

        super(Airport, self).__init__(*args, **kwargs)
        self.id = id
        self.name = name
        self.lat = lat
        self.long = long
        self.land_take_off_price = land_take_off_price
        self.noise_price = noise_price
        self.park_price = park_price
        self.fuel_cost = fuel_cost
        self.cargo_price = cargo_price
        self.airport_dests = []
        self.packages = []
        self.packs_dest = {}

    def remove_packages(self, loaded_packs_from_airport: list):
        self.packages = [pack for pack in self.packages if pack not in loaded_packs_from_airport]
        for package in loaded_packs_from_airport:
            if package.get_dest().get_name() in self.packs_dest:
                self.packs_dest[package.get_dest().get_name()] = self.packs_dest[package.get_dest().get_name()] - 1

    def get_name(self):
        return self.name

    def add_package(self, package):
        """
        If destination points of that airport are not defined
        then add them to that list
        :param package: package to add to the airport
        :return: None
        """
        if package.get_dest() not in self.airport_dests:
            self.airport_dests.append(package.get_dest())
        if package.get_dest().get_name() in self.packs_dest:
            self.packs_dest[package.get_dest().get_name()] = self.packs_dest[package.get_dest().get_name()] + 1
        else:
            self.packs_dest[package.get_dest().get_name()] = 1
        self.packages.append(package)

    # get methods
    def get_start_land_price(self):
        """
        :return: take-off price + loud price
        """
        return self.land_take_off_price + self.noise_price

    def get_fuel_price(self):
        """
        :return: fuel price for 1 l
        """
        return self.fuel_cost

    def get_lat(self):
        return self.lat

    def get_long(self):
        return self.long

    def get_packages_weight(self):
        packages_weight = 0
        for package in self.packages:
            packages_weight += package.get_weight()
        return packages_weight

    def contain_packages(self):
        """
        If in airport context exists al least one package with status WAITING for this airport then return True
        :return:
        """
        for package in AirportContext.get_packages():
            if package.get_status() == Package.WAITING and package.get_post().get_name() == self.name:
                return True
        return False

    def get_packages(self):
        return self.packages

    # get random packages
    def get_random_packages(self, packages_weight):
        packs_to_load = []
        loaded_packs_weight = 0
        while loaded_packs_weight < packages_weight:
            first_package = self.packages.pop()
            loaded_packs_weight += first_package.get_weight()
            packs_to_load.append(first_package)
        return packs_to_load

    def get_airport_dests(self):
        return self.airport_dests

    def get_pack_dests(self):
        return self.packs_dest


class PackageType(models.Model):
    package_type = models.CharField(max_length=10)

    def get_package_type(self):
        return self.package_type


class Package(models.Model):
    weight = models.FloatField(max_length=250)
    post_air_port = models.ForeignKey(Airport, related_name='post_air_port', default=None)
    dest_air_port = models.ForeignKey(Airport, related_name='est_air_port', default=None)
    contents = models.CharField(max_length=250)
    package_type = models.ForeignKey(PackageType)

    DELIVERED = PackageStatus.DELIVERED
    WAITING = PackageStatus.WAITING
    LOADED = PackageStatus.LOADED
    STATUSES = (
        (DELIVERED, 'Delivered'),
        (WAITING, 'Waiting'),
        (LOADED, 'Loaded'),
    )
    status = models.CharField(
        max_length=10,
        choices=STATUSES,
        default=WAITING,
    )

    def get_status(self):
        return self.status

    def get_dest(self) -> Airport:
        return self.dest_air_port

    def get_post(self) -> Airport:
        return self.post_air_port

    def get_weight(self) -> float:
        return self.weight

    def set_status(self, status):
        self.status = status

courier_mb/forms.py
from django import forms


class SignUpForm(forms.Form):
    your_name_surname = forms.CharField(label= "", widget=forms.TextInput(attrs={'placeholder': 'Name & Surname'}), max_length=15)
    your_username = forms.CharField(label= "", widget=forms.TextInput(attrs={'placeholder': 'Username'}), max_length=10)
    email = forms.EmailField(label= "", widget=forms.EmailInput(attrs={'placeholder': 'Email'}), max_length=20)
    password = forms.CharField(label= "", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), max_length=10)
    repeat_password = forms.CharField(label= "", widget=forms.PasswordInput(attrs={'placeholder': 'Repeat password'}), max_length=10)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        repeat_password = cleaned_data.get('repeat_password')

        if password and password != repeat_password:
            msg = "password does not match"
            self.add_error('repeat_password', msg)
        return self.cleaned_data


class LoginForm(forms.Form):
    your_username = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Username'}), max_length=10)
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), max_length=10)

    def clean(self):
        return super().clean()


class SenderForm(forms.Form):
    name_and_surname = forms.CharField(label="Your name and surname", initial='', max_length=20)
    company = forms.CharField(label="Company", initial='', max_length=20)
    country = forms.CharField(label="Country", initial='', max_length=20)
    address = forms.CharField(label="Address", initial='', max_length=20)
    postalCode = forms.CharField(label="Postal Code", initial='', max_length=20)
    city = forms.CharField(label="City", initial='', max_length=20)
    phone = forms.CharField(label="Phone", initial='', max_length=20)
    email = forms.EmailField(label="Email", initial='', max_length=20)

    def clean(self):
        cleaned_data = super().clean()
        address = cleaned_data.get("address")
        city = cleaned_data.get("city")
        if address == "":
            msg = "Provide valid address"
            self.add_error('valid_address', msg)
        if city == "":
            msg = "Provide valid city name"
            self.add_error('valid_address', msg)
        return cleaned_data


class ReceiverForm(forms.Form):
    name_and_surname = forms.CharField(label="Receiver name and surname", initial='', max_length=20)
    company = forms.CharField(label="Company", initial='', max_length=20)
    country = forms.CharField(label="Country", initial='', max_length=20)
    address = forms.CharField(label="Address", initial='', max_length=20)
    postalCode = forms.CharField(label="Postal Code", initial='', max_length=20)
    city = forms.CharField(label="City", initial='', max_length=20)
    phone = forms.CharField(label="Phone", initial='', max_length=20)
    email = forms.EmailField(label="Email", initial='', max_length=20)

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

CourierMB/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, render



def start_page(request):
    return render(request, 'courier_mb/start.html')

courier_mb/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.shortcuts import  render
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from .forms import SignUpForm, LoginForm, SenderForm, ReceiverForm
from django.shortcuts import redirect
from courier_mb.utils import Utils
from courier_mb.models import Airport
from courier_mb.models import Package
from courier_mb.air_fracht_algo.controller.airports_context import AirportContext
from django.contrib.auth.decorators import login_required


@login_required()
def get_home_page(request):
    return render(request, 'courier_mb/home.html')


@login_required()
def get_admin_panel(request):
    if request.user.is_superuser:

        # init AirportContext with airports
        airports = Airport.objects.all()
        AirportContext.init_airports_context(airports)
        num_of_packages_in_database = Package.objects.count()
        return render(request, 'courier_mb/admin_panel.html', {"database_status" : num_of_packages_in_database})
    else:
        status_code = 403
        return HttpResponse("Status code returned: {} .You are not allowed to see this page. Contact with service admin".format(str(status_code)), status=status_code)

@login_required()
def get_my_profile(request):
    return render(request, 'courier_mb/my_profile.html')


def get_signup_form(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SignUpForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            name_surname = form.cleaned_data['your_name_surname']
            name_surname = name_surname.split(" ")
            user = User.objects.create_user(form.cleaned_data['your_username'], form.cleaned_data['email'],
                                            form.cleaned_data['password'])
            user.first_name = name_surname[0]
            if len(name_surname) > 1:
                user.last_name = name_surname[1]
            user.save()
            return HttpResponseRedirect('/courierMB/home')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SignUpForm()

    return render(request, 'courier_mb/sgn_log_form.html', {'form': form, 'signup': True})


def get_login_form(request):
    # static variables
    no_user_message = 'There is no user with given credentials'
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['your_username'], password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/courierMB/home')
            else:
                messages.add_message(request, messages.INFO, no_user_message)
                return HttpResponseRedirect('/courierMB/login')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = LoginForm()

    return render(request, 'courier_mb/sgn_log_form.html', {'form': form, 'signup': False})


@login_required()
def get_package_details_page(request):
    return render(request, 'package_details_page.html')


@login_required()
def get_send_package_page(request):
    # check whether it's valid:
    if request.method == 'POST':
        senderForm = SenderForm(request.POST)
        receiverForm = ReceiverForm(request.POST)
        print("post works!!!")
        if senderForm.is_valid() and receiverForm.is_valid():
            # sender_data = Utils.get_form_data(senderForm, senderForm.cleaned_data)
            # receiver_data = Utils.get_form_data(receiverForm, receiverForm.cleaned_data)
            print("valid")
            return get_package_type_page(request, senderForm.cleaned_data, receiverForm.cleaned_data)
            # return HttpResponseRedirect('/courierMB/package_details')
    else:
        senderForm = SenderForm()
        receiverForm = ReceiverForm()
    return render(request, 'courier_mb/transfer_details.html', {'senderForm': senderForm, 'receiverForm': receiverForm})


@login_required()
def get_package_type_page(request, sender_data, receiver_data):
    return render(request, 'courier_mb/transfer_details.html', {'sender_data': sender_data, 'receiver_data' : receiver_data})

courier_mb/templates/courier_mb/address_data_form.html
{% extends "courier_mb/layout.html" %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/address_data.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
{% endblock %}

<!-- 16.51 -->
{% block content %}
    <div style="width: 100%;">
       <div id="send_receive_form_cont">
           <form id="send_receive_address_form" action="" method="post">
                {% csrf_token %}
               <div id="sender_form_cont">
                   <h1>Sender address</h1>
                    {{ senderForm.as_p }}
               </div>
               <div id="receiver_form_cont">
                   <h1>Receiver address</h1>
                    {{ receiverForm.as_p }}
               </div>
               <div style="text-align: center;">
                    <input id="addressBtn" class="button" type="submit" value="Continue">
               </div>
            </form>
       </div>
    </div>
{% endblock %}

courier_mb/templates/courier_mb/admin_panel.html
{% extends "courier_mb/layout.html" %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/admin_panel.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <script src="{% static 'js/admin_panel.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
{% endblock %}

{% block content %}
<div id="admin_panel_area">
    <div id="admin_panel_run_section" style="z-index: 5;">
        <h1>Database section</h1>
        <hr>
        <div>
            <h3 style="display: inline-block; width: 40%;">Packages in database: </h3><label id="admin_panel_packages_status">{{ database_status }}</label>
        </div>
        <div>
            <h3 style="display: inline-block; width: 40%;">Add packages: </h3><input style="width: 300px;" id="admin_panel_add_packages_input" type="text"/>
        </div>
        <button class="button" onclick="add_to_database()">Add packages</button>
        <div>
            <h3 style="display: inline-block; width: 40%;">Remove packages: </h3><input style="width: 300px;" id="admin_panel_remove_packages_input" type="text"/>
        </div>
        <div style="margin-bottom: 16px;">
            <button class="button" onclick="remove_packages()">Remove packages</button>
        </div>
        <div>
            <button class="button" onclick="clear_database()">Clear database</button>
        </div>
    </div>
    <div id="admin_panel_run_section" style="z-index: 5;">
        <h1>Run algorithm</h1>
        <hr>
        <button class="button" onclick="run_algorithm()">RUN ALGORITHM</button>
    </div>
    <div id="admin_panel_results_section">
        <div>
            <h1>Results section</h1>
        </div>
        <hr>
        <div>
            <h3 style="display: inline-block; width: 40%;">Price for tour: </h3><label id="admin_panel_price_for_tour">0</label>
        </div>
        <div>
            <h3 style="display: inline-block; width: 40%;">Earnings from packages: </h3><label id="admin_panel_earnings_from_packages">0</label>
        </div>
        <div>
            <h3 style="display: inline-block; width: 40%;">Total earnings: </h3><label id="admin_panel_total_earnings">0</label>
        </div>
        <div>
            <h1>Final tour results</h1>
        </div>
        <hr>
        <div>
            <h2><label id="admin_panel_trip_order">Best trip order</label></h2>
        </div>
    </div>
</div>

{% endblock %}

courier_mb/templates/courier_mb/home.html
{% extends "courier_mb/layout.html" %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="{% static 'js/drop_down_menu.js' %}"></script>
{% endblock %}

{% block title %}CourierMB{% endblock %}
{% block content %}
    <nav id="menu_nav">
      <ul>
        <li>
          <a href="#">SEND</a>
          <ul class="fallback">
            <li><a href="{% url 'courier_mb:send_package_page' %}">send international package</a></li>
            <li><a href="#">send local package</a></li>
          </ul>
        </li>
        <li>
          <a href="#">TRACK</a>
          <ul class="fallback">
            <li><a href="#">track your package</a></li>
            <li><a href="#">track your package in country</a></li>
          </ul>
        </li>
          <li>
          <a href="#">CONTACT</a>
          <ul class="fallback">
          </ul>
        </li>
          <li>
              <a href="#">ABOUT US</a>
              <ul class="fallback">
              </ul>
        </li>
      </ul>
    </nav>
    <div>
        <img src="{% static 'images/home_photo_2.jpg' %}" alt="Home view" style="width:100%;height:auto">
    </div>
    <div id="home_info_section">
        <p>
            Air Freight is the fastest way to deliver goods to a specific destination worldwide.
        </p>
        <p>
            Air transport alongside maritime and road transport and agencies
             Customs is one of the basic services provided to our customers by our company.
        </p>
        <p>
            CourierMB offers reliable air freight services for all high-priority shipments - completely according to individual needs.
            We provide complete services for air freight solutions: standard products,
            express mail, charters, on board couriers, door-to-door delivery, heavy goods transport, dangerous goods transport, cargo charters, perishable goods.
        </p>
        <p>
            In our company we offer:
        </p>
        <p>
           <ol id="home_offer_list">
                <li>Direct shipping and delivery to all major world airports in import and export</li>
                <li>Delivery: door to door, airport to airport, airport to door, airport to airport and any delivery terms according to INCOTRMS</li>
                <li>Air freight perishable goods.</li>
                <li>Air freight DGR goods</li>
                <li>Air freight valuation VAL</li>
                <li>Air freight airport property.</li>
                <li>Freight of other untypical goods</li>
                <li>Freight of goods for fairs and exhibitions (ATA carnet)</li>
            </ol>
        </p>
    </div>
{% endblock %}

courier_mb/templates/courier_mb/layout.html
{% load static from staticfiles %}

<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        <script src="{% static "js/jquery-1.8.0.min.js" %}"></script>
        <script src="{% static "js/jquery-ui.js" %}"></script>
        <script src="{% static "js/jquery-ui.min.js" %}"></script>
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
        {% block static %}{% endblock %}
    </head>
    <body>
        <div class="site-container" style="position: relative;">
            <h1 id="logo">CourierMB</h1>
            <nav id="layout_nav">
                <a href="{% url 'courier_mb:home_page' %}">Home</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'courier_mb:logout' %}">log out</a>
                {% else %}
                    <a href="{% url 'courier_mb:login_form' %}">log in</a>
                {% endif %}
            </nav>
            <div id="main_page_cont_id">
                {% block content %}{% endblock %}
            </div>
        </div>
    </body>
</html>

courier_mb/templates/courier_mb/my_profile.html
{% extends "courier_mb/layout.html" %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/address_data.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
{% endblock %}

{% block content %}


{% endblock %}

courier_mb/templates/courier_mb/sgn_log_form.html
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/signup_form.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
{% endblock %}

{% block content %}
    <div id="container" style="position: relative">
        <div id="form_container" style="position: absolute;">
            <div id="content_container" style="position: absolute;">
                <div>
                    <h1>CourierMB</h1>
                </div>
                <div>
                    <h2>Create your account to send packages to places around the world</h2>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <form id="signup_form" action="" method="post">
                    {% csrf_token %}
                    {{ form }}
                    {% if  signup %}
                    <!--this is signup form-->
                        <input id="sbt_btn" type="submit" value="Sign up">
                    {% else %}
                    <!--this is login form-->
                        <input id="sbt_btn" type="submit" value="Log in">
                    {% endif %}
                </form>
                {% if signup %}
                    <div>
                        <p>You already have account? <a href="{% url 'courier_mb:login_form' %} "/>Log in</p>
                    </div>
                {% elif not signup %}
                    <div>
                        <p>Not a member yet? Sign up <a href="{% url 'courier_mb:sign_up_form' %} "/>Sign up</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

courier_mb/templates/courier_mb/start.html
{% extends "courier_mb/layout.html" %}

{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/start.css' %}">
{% endblock %}

{% block title %}CourierMB{% endblock %}

{% block content %}
    <div id="container" style="position: relative;">
        <div id="start_plane_cont" style="position: absolute;">
           <img id="start_plane" src="{% static 'images/plane.png' %}" alt="plane">
        </div>
        <div id="start_text_cont" style="position: absolute;">
            <p id="start_text">Send your packages any time you want,
                anywhere you want,
                for the lowest prices
                on the market with CourierMB.
            </p>
        </div>
        <div id="start_btn_cont" style="position: absolute;">
            <form action="{% url 'courier_mb:login_form' %}" method="get">
                <input id="start_btn" type="submit" value="START" />
            </form>
        </div>
    </div>
{% endblock %}