CourierMB/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

from . import views


urlpatterns = [
    url(r'^courierMB/', include('courier_mb.urls', namespace='courier_mb')),
    url(r'^start/', views.start_page),
    url(r'^admin/', admin.site.urls),
]

courier_mb/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from . import actions
from django.conf.urls import include
from rest_framework import routers
from django.contrib.auth import views as auth_views




urlpatterns = [

    #actions
    url(r'^actions/save_package/$', actions.save_package, name="save_package"),
    url(r'^actions/run_computations/$', actions.run_computations, name="run_computations"),
    url(r'^actions/get_airport/$', actions.get_airport, name="get_airport"),
    url(r'^actions/logout/$',actions.logout_action, name="logout"),
    url(r'^actions/init_database/$',actions.init_database, name="init_database"),
    url(r'^actions/add_to_database/$', actions.add_to_database, name="add_to_database"),
    url(r'^actions/clear_database/$', actions.clear_database, name="clear_database"),
    url(r'^actions/remove_packages/$', actions.remove_packages, name="remove_packages"),

    #views
    url(r'^home/$', views.get_home_page, name="home_page"),
    url(r'^package_details/$', views.get_package_details_page, name="package_details_page"),
    url(r'^profile/$', views.get_my_profile, name="my_profile"),
    url(r'^login/$', views.get_login_form, name="login_form"),
    url(r'^admin_panel/$', views.get_admin_panel, name="admin_panel"),
    url(r'^signup/$', views.get_signup_form, name="sign_up_form"),
    url(r'^send_inter_package/$', views.get_send_package_page, name="send_package_page"),
]

templates/address_data_form.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/address_data.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
{% endblock %}

<!-- 16.51 -->
{% block content %}
    <div style="width: 100%;">
       <div id="send_receive_form_cont">
           <form id="send_receive_address_form" action="" method="post">
                {% csrf_token %}
               <div id="sender_form_cont">
                   <h1>Sender address</h1>
                    {{ senderForm.as_p }}
               </div>
               <div id="receiver_form_cont">
                   <h1>Receiver address</h1>
                    {{ receiverForm.as_p }}
               </div>
               <div style="text-align: center;">
                    <input id="address_btn" class="button" type="submit" value="Continue">
               </div>
            </form>
       </div>
    </div>
{% endblock %}

templates/home.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="{% static 'js/drop_down_menu.js' %}"></script>
{% endblock %}

{% block title %}CourierMB{% endblock %}
{% block content %}
    <nav id="menu_nav">
      <ul>
        <li>
          <a href="#">SEND</a>
          <ul class="fallback">
            <li><a href="{% url 'courier_mb:send_package_page' %}">send international package</a></li>
            <li><a href="#">send local package</a></li>
          </ul>
        </li>
        <li>
          <a href="#">TRACK</a>
          <ul class="fallback">
            <li><a href="#">track your package</a></li>
            <li><a href="#">track your package in country</a></li>
          </ul>
        </li>
      </ul>
    </nav>
    <p id="desc_element">Desc element</p>
    <div id="test_div">
        <p>this is a test div</p>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">

        <script src="{% static "js/jquery-1.8.0.min.js" %}"></script>
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
        {% block static %}{% endblock %}
    </head>
    <body>
        <div class="site-container" style="position: relative;">
            <h1 id="logo">CourierMB</h1>
            <nav id="layout_nav">
                <a href="{% url 'courier_mb:home_page' %}">Home</a>
                <a href="{% url 'courier_mb:my_profile' %}">My Profile</a>
            </nav>
            <div id="main_page_cont_id">
                {% block content %}{% endblock %}
            </div>
        </div>
    </body>
</html>

templates/sgn_log_form.html
{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/signup_form.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
{% endblock %}

{% block content %}
    <div id="container" style="position: relative">
        <div id="form_container" style="position: absolute;">
            <div id="content_container" style="position: absolute;">
                <div>
                    <h1>CourierMB</h1>
                </div>
                <div>
                    <h2>Create your account to send packages to places around the world</h2>
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <form id="signup_form" action="" method="post">
                    {% csrf_token %}
                    {{ form }}
                    {% if  signup %}
                    <!--this is signup form-->
                        <input id="sbt_btn" type="submit" value="Sign up">
                    {% else %}
                    <!--this is login form-->
                        <input id="sbt_btn" type="submit" value="Log in">
                    {% endif %}
                </form>
                {% if signup %}
                    <div>
                        <p>You already have account? <a href="{% url 'courier_mb:log_in_form' %} "/>Log in</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/start.html
{% extends "layout.html" %}

{% load static from staticfiles %}

{% block static %}
    <link rel="stylesheet" href="{% static 'css/start.css' %}">
{% endblock %}

{% block title %}CourierMB{% endblock %}

{% block content %}
    <div id="container" style="position: relative;">
        <div id="start_plane_cont" style="position: absolute;">
           <img id="start_plane" src="{% static 'images/plane.png' %}" alt="plane">
        </div>
        <div id="start_text_cont" style="position: absolute;">
            <p id="start_text">Send your packages any time you want,
                anywhere you want,
                for the lowest prices
                on the market with CourierMB.
            </p>
        </div>
        <div id="start_btn_cont" style="position: absolute;">
            <form action="{% url 'courier_mb:sign_up_form' %}" method="get">
                <input id="start_btn" type="submit" value="START" />
            </form>
        </div>
    </div>
{% endblock %}